name: Deploy MultiDocker
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build development image
        run: docker build -t ballour/react-test -f ./client/Dockerfile.dev ./client

      - name: Run tests
        run: docker run -e CI=true ballour/react-test npm test

      - name: Build production images
        run: |
          docker build -t ballour/multi-client ./client
          docker build -t ballour/multi-nginx ./nginx
          docker build -t ballour/multi-server ./server
          docker build -t ballour/multi-worker ./worker

      - name: Release production images in Dockerhub
        run: |
          docker push ballour/multi-client
          docker push ballour/multi-nginx
          docker push ballour/multi-server
          docker push ballour/multi-worker
